- name: Check for required variables
  fail: 
    msg: "{{ item }} is required"
  when: item is not defined or item | length == 0
  loop:
    - "{{ nginx_hosts }}"
    - "{{ nginx_letsencrypt_email }}"
  tags:
    - http

- name: Check .htpasswd credential variables
  fail:
    msg: "{{ item }} is required when .htpasswd support is enabled"
  when: nginx_use_htpasswd and (item is not defined or item | length == 0)
  loop:
    - "{{ nginx_htpasswd_username }}"
    - "{{ nginx_htpasswd_hashed_password }}"
  tags:
    - http

- name: Installing nginx and certbot
  apt:
    pkg:
      - nginx
      - certbot
  tags:
    - http
    - streams
    - install

- name: Enabling nginx service
  service:
    enabled: yes
    name: nginx
  tags:
    - http
    - streams
    - install

- name: Copy custom error pages snippet config
  copy:
    src: "error_pages.conf"
    dest: "/etc/nginx/snippets/error_pages.conf"
    owner: root
    group: root
    mode: "644"
  notify: Restart nginx
  tags:
    - http

- name: Copy custom error pages
  template:
    src: "var/www/html/{{ item }}.j2"
    dest: "/var/www/html/{{ item }}"
    owner: root
    group: root
    mode: "644"
  loop:
    - "401.html"
    - "403.html"
    - "404.html"
  tags:
    - http

- name: Get DH params
  get_url:
    dest: "{{ nginx_ssl_dhparams_path }}"
    owner: root
    group: root
    mode: '664'
    url: "https://ssl-config.mozilla.org/ffdhe4096.txt"
  tags:
    - http

- name: Copying nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx
  tags:
    - http
    - streams

- name: Copy nginx password
  template:
    src: .htpasswd.j2
    dest: /etc/nginx/.htpasswd
  notify: Restart nginx
  when: nginx_use_htpasswd | bool
  tags:
    - http

- name: Creating srv directories
  file:
    state: directory
    path: /srv/http/{{ item.name }}
  with_items: "{{ nginx_hosts }}"
  when: nginx_hosts is defined
  tags:
    - http

- name: Creating challenge directory
  file:
    state: directory
    path: /var/lib/letsencrypt/.well-known/acme-challenge
    owner: www-data
    group: www-data
    mode: '02775'
  notify: Restart nginx
  tags:
    - http

- name: Ensure hosts directory exists
  file:
    state: directory
    path: /etc/nginx/hosts
  tags:
    - http

- name: Ensure streams directory exists
  file:
    state: directory
    path: /etc/nginx/streams
  tags:
    - streams

- name: Check for existing HTTPS configs
  stat:
    path: "/etc/nginx/hosts/{{ item.name }}.https.conf"
  with_items: "{{ nginx_hosts }}"
  when: nginx_hosts is defined
  register: stats
  tags:
    - http

- name: Deploy temporary HTTP Nginx configurations
  template:
    src: hosts/host.http.conf.j2
    dest: "/etc/nginx/hosts/{{ item.item.name }}.http.conf"
  with_items: "{{ stats.results }}"
  when: not item.stat.exists
  notify: Restart nginx
  tags:
    - http

- name: Flush handlers
  meta: flush_handlers
  tags:
    - http
    - streams

- name: Using Certbot to get certificates
  command: >
    certbot certonly
      --quiet
      --agree-tos
      --expand
      --email {{ nginx_letsencrypt_email }}
      --webroot
      -w /var/lib/letsencrypt/
      -d {{ item.item.name }}
      {% if item.item.redirect_www is defined and item.item.redirect_www %}
      -d www.{{ item.item.name }}
      {% endif %}
  with_items: "{{ stats.results }}"
  when: not item.stat.exists
  notify: Restart nginx
  tags:
    - http

- name: Remove temporary HTTP sites
  file:
    path: "/etc/nginx/hosts/{{ item.item.name }}.http.conf"
    state: absent
  with_items: "{{ stats.results }}"
  when: not item.stat.exists
  tags:
    - http

- name: Deploy HTTPS Nginx configurations
  template:
    src: hosts/host.https.conf.j2
    dest: "/etc/nginx/hosts/{{ item.name }}.https.conf"
  with_items: "{{ nginx_hosts }}"
  when: nginx_hosts is defined
  notify: Restart nginx
  tags:
    - http

- name: Deploy TCP/UDP load balancer streams
  template:
    src: streams/stream.conf.j2
    dest: "/etc/nginx/streams/{{ item.name }}.conf"
  with_items: "{{ nginx_streams }}"
  when: nginx_streams is defined
  notify: Restart nginx
  tags:
    - streams
