- name: Restart nginx
  command: nginx -t
  become: true
  register: nginx_out
  notify: restart_nginx_stage_2

- name: restart_nginx_stage_2
  service:
    name: nginx
    state: restarted
  become: true
  when: nginx_out.rc == 0
