- name: Check nginx config
  command: nginx -t
  become: true
  register: nginx_out
  listen: Restart nginx

- name: Restart nginx service
  service:
    name: nginx
    state: restarted
  become: true
  when: nginx_out.rc == 0
  listen: Restart nginx
